# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fcm_create.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(855, 753)
        self.gridLayout_13 = QtWidgets.QGridLayout(Form)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 0, 0, 1, 2)
        self.btn_loadData = QtWidgets.QPushButton(Form)
        self.btn_loadData.setStyleSheet("background-color: rgb(210, 255, 229);\n"
"font: 63 11pt \"FreeSans\";")
        self.btn_loadData.setObjectName("btn_loadData")
        self.gridLayout_13.addWidget(self.btn_loadData, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 1, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 3, 0, 1, 1)
        self.list_cm = QtWidgets.QListWidget(self.tab)
        self.list_cm.setStyleSheet("font: 11pt \"FreeMono\";")
        self.list_cm.setObjectName("list_cm")
        self.gridLayout_11.addWidget(self.list_cm, 1, 1, 3, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_info1 = QtWidgets.QLabel(self.widget_2)
        self.label_info1.setObjectName("label_info1")
        self.gridLayout_14.addWidget(self.label_info1, 0, 0, 1, 1)
        self.label_info2 = QtWidgets.QLabel(self.widget_2)
        self.label_info2.setObjectName("label_info2")
        self.gridLayout_14.addWidget(self.label_info2, 1, 0, 1, 1)
        self.label_info3 = QtWidgets.QLabel(self.widget_2)
        self.label_info3.setObjectName("label_info3")
        self.gridLayout_14.addWidget(self.label_info3, 2, 0, 1, 1)
        self.label_info4 = QtWidgets.QLabel(self.widget_2)
        self.label_info4.setObjectName("label_info4")
        self.gridLayout_14.addWidget(self.label_info4, 3, 0, 1, 1)
        self.label_info5 = QtWidgets.QLabel(self.widget_2)
        self.label_info5.setObjectName("label_info5")
        self.gridLayout_14.addWidget(self.label_info5, 4, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget_2, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setMaximumSize(QtCore.QSize(370, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_eutid = QtWidgets.QComboBox(self.widget)
        self.comboBox_eutid.setObjectName("comboBox_eutid")
        self.gridLayout_2.addWidget(self.comboBox_eutid, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 1, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 1, 1, 1, 1)
        self.label_name = QtWidgets.QLabel(self.widget)
        self.label_name.setObjectName("label_name")
        self.gridLayout_2.addWidget(self.label_name, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout_2.addWidget(self.lineEdit_name, 2, 1, 1, 1)
        self.label_info = QtWidgets.QLabel(self.widget)
        self.label_info.setObjectName("label_info")
        self.gridLayout_2.addWidget(self.label_info, 3, 0, 1, 1)
        self.lineEdit_info = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_info.setObjectName("lineEdit_info")
        self.gridLayout_2.addWidget(self.lineEdit_info, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.widget)
        self.label_83.setObjectName("label_83")
        self.gridLayout_2.addWidget(self.label_83, 5, 0, 1, 1)
        self.comboBox_ambtempid = QtWidgets.QComboBox(self.widget)
        self.comboBox_ambtempid.setObjectName("comboBox_ambtempid")
        self.gridLayout_2.addWidget(self.comboBox_ambtempid, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 6, 0, 1, 1)
        self.comboBox_testloadid = QtWidgets.QComboBox(self.widget)
        self.comboBox_testloadid.setObjectName("comboBox_testloadid")
        self.gridLayout_2.addWidget(self.comboBox_testloadid, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.widget)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_fileName = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_fileName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.gridLayout.addWidget(self.lineEdit_fileName, 4, 1, 1, 3)
        self.btn_addMeasurment = QtWidgets.QPushButton(self.widget_11)
        self.btn_addMeasurment.setStyleSheet("")
        self.btn_addMeasurment.setObjectName("btn_addMeasurment")
        self.gridLayout.addWidget(self.btn_addMeasurment, 5, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 2)
        self.btn_openfile = QtWidgets.QPushButton(self.widget_11)
        self.btn_openfile.setObjectName("btn_openfile")
        self.gridLayout.addWidget(self.btn_openfile, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 4)
        self.gridLayout_2.addWidget(self.widget_11, 10, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 1)
        self.comboBox_sensortyplistid = QtWidgets.QComboBox(self.widget)
        self.comboBox_sensortyplistid.setObjectName("comboBox_sensortyplistid")
        self.gridLayout_2.addWidget(self.comboBox_sensortyplistid, 9, 1, 1, 1)
        self.gridLayout_11.addWidget(self.widget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.frame_16 = QtWidgets.QFrame(self.tab_3)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.list_sensorTypListofLists = QtWidgets.QListWidget(self.frame_16)
        self.list_sensorTypListofLists.setObjectName("list_sensorTypListofLists")
        self.gridLayout_39.addWidget(self.list_sensorTypListofLists, 1, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.frame_16)
        self.label_82.setObjectName("label_82")
        self.gridLayout_39.addWidget(self.label_82, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.frame_16, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 816, 360))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 6, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_28 = QtWidgets.QLabel(self.widget_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget_7)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_5.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_5.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_5.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_5.addWidget(self.comboBox_6, 5, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_5.addWidget(self.comboBox_7, 6, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_5.addWidget(self.comboBox_8, 7, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_5.addWidget(self.comboBox_9, 8, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.widget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 9, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.widget_7)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_5.addWidget(self.comboBox_10, 9, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_7, 0, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_13 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_6.addWidget(self.comboBox_13, 3, 1, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout_6.addWidget(self.comboBox_17, 7, 1, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout_6.addWidget(self.comboBox_18, 8, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget_8)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 10, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_8)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 0, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_19.setObjectName("comboBox_19")
        self.gridLayout_6.addWidget(self.comboBox_19, 9, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_6.addWidget(self.comboBox_11, 0, 1, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_20.setObjectName("comboBox_20")
        self.gridLayout_6.addWidget(self.comboBox_20, 10, 1, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout_6.addWidget(self.comboBox_15, 5, 1, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_6.addWidget(self.comboBox_14, 4, 1, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout_6.addWidget(self.comboBox_16, 6, 1, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.widget_8)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_6.addWidget(self.comboBox_12, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_8, 0, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_44 = QtWidgets.QLabel(self.widget_9)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_21.setObjectName("comboBox_21")
        self.gridLayout_7.addWidget(self.comboBox_21, 0, 1, 1, 1)
        self.comboBox_22 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_22.setObjectName("comboBox_22")
        self.gridLayout_7.addWidget(self.comboBox_22, 1, 1, 1, 1)
        self.comboBox_23 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_23.setObjectName("comboBox_23")
        self.gridLayout_7.addWidget(self.comboBox_23, 2, 1, 1, 1)
        self.comboBox_24 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_24.setObjectName("comboBox_24")
        self.gridLayout_7.addWidget(self.comboBox_24, 3, 1, 1, 1)
        self.comboBox_25 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_25.setObjectName("comboBox_25")
        self.gridLayout_7.addWidget(self.comboBox_25, 4, 1, 1, 1)
        self.comboBox_26 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_26.setObjectName("comboBox_26")
        self.gridLayout_7.addWidget(self.comboBox_26, 5, 1, 1, 1)
        self.comboBox_27 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_27.setObjectName("comboBox_27")
        self.gridLayout_7.addWidget(self.comboBox_27, 6, 1, 1, 1)
        self.comboBox_28 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_28.setObjectName("comboBox_28")
        self.gridLayout_7.addWidget(self.comboBox_28, 7, 1, 1, 1)
        self.comboBox_29 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_29.setObjectName("comboBox_29")
        self.gridLayout_7.addWidget(self.comboBox_29, 8, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget_9)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 9, 0, 1, 1)
        self.comboBox_30 = QtWidgets.QComboBox(self.widget_9)
        self.comboBox_30.setObjectName("comboBox_30")
        self.gridLayout_7.addWidget(self.comboBox_30, 9, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_9, 0, 2, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_46 = QtWidgets.QLabel(self.widget_13)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 0, 0, 1, 1)
        self.comboBox_31 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_31.setObjectName("comboBox_31")
        self.gridLayout_8.addWidget(self.comboBox_31, 0, 1, 1, 1)
        self.comboBox_32 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_32.setObjectName("comboBox_32")
        self.gridLayout_8.addWidget(self.comboBox_32, 1, 1, 1, 1)
        self.comboBox_33 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_33.setObjectName("comboBox_33")
        self.gridLayout_8.addWidget(self.comboBox_33, 2, 1, 1, 1)
        self.comboBox_34 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_34.setObjectName("comboBox_34")
        self.gridLayout_8.addWidget(self.comboBox_34, 3, 1, 1, 1)
        self.comboBox_35 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_35.setObjectName("comboBox_35")
        self.gridLayout_8.addWidget(self.comboBox_35, 4, 1, 1, 1)
        self.comboBox_36 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_36.setObjectName("comboBox_36")
        self.gridLayout_8.addWidget(self.comboBox_36, 5, 1, 1, 1)
        self.comboBox_37 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_37.setObjectName("comboBox_37")
        self.gridLayout_8.addWidget(self.comboBox_37, 6, 1, 1, 1)
        self.comboBox_38 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_38.setObjectName("comboBox_38")
        self.gridLayout_8.addWidget(self.comboBox_38, 7, 1, 1, 1)
        self.comboBox_39 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_39.setObjectName("comboBox_39")
        self.gridLayout_8.addWidget(self.comboBox_39, 8, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.widget_13)
        self.label_76.setObjectName("label_76")
        self.gridLayout_8.addWidget(self.label_76, 9, 0, 1, 1)
        self.comboBox_40 = QtWidgets.QComboBox(self.widget_13)
        self.comboBox_40.setObjectName("comboBox_40")
        self.gridLayout_8.addWidget(self.comboBox_40, 9, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_13, 0, 3, 1, 1)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.comboBox_41 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_41.setObjectName("comboBox_41")
        self.gridLayout_9.addWidget(self.comboBox_41, 0, 1, 1, 1)
        self.comboBox_42 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_42.setObjectName("comboBox_42")
        self.gridLayout_9.addWidget(self.comboBox_42, 1, 1, 1, 1)
        self.comboBox_43 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_43.setObjectName("comboBox_43")
        self.gridLayout_9.addWidget(self.comboBox_43, 2, 1, 1, 1)
        self.comboBox_44 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_44.setObjectName("comboBox_44")
        self.gridLayout_9.addWidget(self.comboBox_44, 3, 1, 1, 1)
        self.comboBox_45 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_45.setObjectName("comboBox_45")
        self.gridLayout_9.addWidget(self.comboBox_45, 4, 1, 1, 1)
        self.comboBox_46 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_46.setObjectName("comboBox_46")
        self.gridLayout_9.addWidget(self.comboBox_46, 5, 1, 1, 1)
        self.comboBox_47 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_47.setObjectName("comboBox_47")
        self.gridLayout_9.addWidget(self.comboBox_47, 6, 1, 1, 1)
        self.comboBox_48 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_48.setObjectName("comboBox_48")
        self.gridLayout_9.addWidget(self.comboBox_48, 7, 1, 1, 1)
        self.comboBox_49 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_49.setObjectName("comboBox_49")
        self.gridLayout_9.addWidget(self.comboBox_49, 8, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.widget_14)
        self.label_78.setObjectName("label_78")
        self.gridLayout_9.addWidget(self.label_78, 9, 0, 1, 1)
        self.comboBox_50 = QtWidgets.QComboBox(self.widget_14)
        self.comboBox_50.setObjectName("comboBox_50")
        self.gridLayout_9.addWidget(self.comboBox_50, 9, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.widget_14)
        self.label_77.setObjectName("label_77")
        self.gridLayout_9.addWidget(self.label_77, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_14, 0, 4, 1, 1)
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.comboBox_57 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_57.setObjectName("comboBox_57")
        self.gridLayout_10.addWidget(self.comboBox_57, 6, 2, 1, 1)
        self.comboBox_52 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_52.setObjectName("comboBox_52")
        self.gridLayout_10.addWidget(self.comboBox_52, 1, 2, 1, 1)
        self.comboBox_55 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_55.setObjectName("comboBox_55")
        self.gridLayout_10.addWidget(self.comboBox_55, 4, 2, 1, 1)
        self.comboBox_56 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_56.setObjectName("comboBox_56")
        self.gridLayout_10.addWidget(self.comboBox_56, 5, 2, 1, 1)
        self.comboBox_54 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_54.setObjectName("comboBox_54")
        self.gridLayout_10.addWidget(self.comboBox_54, 3, 2, 1, 1)
        self.comboBox_58 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_58.setObjectName("comboBox_58")
        self.gridLayout_10.addWidget(self.comboBox_58, 7, 2, 1, 1)
        self.comboBox_59 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_59.setObjectName("comboBox_59")
        self.gridLayout_10.addWidget(self.comboBox_59, 8, 2, 1, 1)
        self.comboBox_51 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_51.setObjectName("comboBox_51")
        self.gridLayout_10.addWidget(self.comboBox_51, 0, 2, 1, 1)
        self.comboBox_53 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_53.setObjectName("comboBox_53")
        self.gridLayout_10.addWidget(self.comboBox_53, 2, 2, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.widget_15)
        self.label_80.setObjectName("label_80")
        self.gridLayout_10.addWidget(self.label_80, 9, 1, 1, 1)
        self.comboBox_60 = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_60.setObjectName("comboBox_60")
        self.gridLayout_10.addWidget(self.comboBox_60, 9, 2, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.widget_15)
        self.label_79.setObjectName("label_79")
        self.gridLayout_10.addWidget(self.label_79, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_15, 0, 5, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 3, 0, 1, 4)
        self.lineEdit_createSensorTypList2_name = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_createSensorTypList2_name.setMinimumSize(QtCore.QSize(260, 0))
        self.lineEdit_createSensorTypList2_name.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_createSensorTypList2_name.setObjectName("lineEdit_createSensorTypList2_name")
        self.gridLayout_4.addWidget(self.lineEdit_createSensorTypList2_name, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.tab_4)
        self.label_81.setObjectName("label_81")
        self.gridLayout_4.addWidget(self.label_81, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 2, 2, 1, 1)
        self.btn_createSensorTypList2 = QtWidgets.QPushButton(self.tab_4)
        self.btn_createSensorTypList2.setObjectName("btn_createSensorTypList2")
        self.gridLayout_4.addWidget(self.btn_createSensorTypList2, 4, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_12.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_13.addWidget(self.tabWidget, 2, 0, 1, 4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 0, 2, 1, 2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Create CM from MCPS Statistic</span></p></body></html>"))
        self.btn_loadData.setText(_translate("Form", "load data from database"))
        self.label_4.setText(_translate("Form", "Climatic Measurement List:"))
        self.label_info1.setText(_translate("Form", "---"))
        self.label_info2.setText(_translate("Form", "---"))
        self.label_info3.setText(_translate("Form", "---"))
        self.label_info4.setText(_translate("Form", "---"))
        self.label_info5.setText(_translate("Form", "---"))
        self.label_23.setText(_translate("Form", "Datum:"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "yyyy.MM.dd-HH:mm:ss"))
        self.label_name.setText(_translate("Form", "Name:"))
        self.label_info.setText(_translate("Form", "Info:"))
        self.label_2.setText(_translate("Form", "EUT: (id)"))
        self.label_83.setText(_translate("Form", "Ambient Temp.: (id)"))
        self.label.setText(_translate("Form", "Test Load: (id)"))
        self.label_7.setText(_translate("Form", "SensorTyp List: (id)"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.btn_addMeasurment.setText(_translate("Form", "add measurement"))
        self.btn_openfile.setText(_translate("Form", "open File"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Create"))
        self.label_82.setText(_translate("Form", "List of all SensorTyp Lists:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "View Typ List"))
        self.label_28.setText(_translate("Form", "1"))
        self.label_39.setText(_translate("Form", "10"))
        self.label_43.setText(_translate("Form", "20"))
        self.label_42.setText(_translate("Form", "11"))
        self.label_44.setText(_translate("Form", "21"))
        self.label_45.setText(_translate("Form", "30"))
        self.label_46.setText(_translate("Form", "31"))
        self.label_76.setText(_translate("Form", "40"))
        self.label_78.setText(_translate("Form", "50"))
        self.label_77.setText(_translate("Form", "41"))
        self.label_80.setText(_translate("Form", "60"))
        self.label_79.setText(_translate("Form", "51"))
        self.label_15.setText(_translate("Form", "sensorTypList_Name:"))
        self.label_81.setText(_translate("Form", "Define the Sensor Type List"))
        self.btn_createSensorTypList2.setText(_translate("Form", "Add Typ List"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Create Typ List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sensor Typ"))

