# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cm_create.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1415, 836)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setMinimumSize(QtCore.QSize(390, 700))
        self.widget_5.setMaximumSize(QtCore.QSize(390, 9000))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_24 = QtWidgets.QLabel(self.widget_5)
        self.label_24.setStyleSheet("font: 63 14pt \"Ubuntu\";")
        self.label_24.setObjectName("label_24")
        self.gridLayout_17.addWidget(self.label_24, 0, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.widget_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_17.addWidget(self.label_21, 1, 0, 1, 2)
        self.btn_loadData = QtWidgets.QPushButton(self.widget_5)
        self.btn_loadData.setStyleSheet("background-color: rgb(210, 255, 229);\n"
"font: 63 11pt \"FreeSans\";")
        self.btn_loadData.setObjectName("btn_loadData")
        self.gridLayout_17.addWidget(self.btn_loadData, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(438, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setObjectName("widget")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.comboBox_testloadid = QtWidgets.QComboBox(self.widget)
        self.comboBox_testloadid.setObjectName("comboBox_testloadid")
        self.gridLayout_13.addWidget(self.comboBox_testloadid, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_13.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.label_name = QtWidgets.QLabel(self.widget)
        self.label_name.setObjectName("label_name")
        self.gridLayout_13.addWidget(self.label_name, 1, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout_13.addWidget(self.lineEdit_name, 1, 1, 1, 1)
        self.label_info = QtWidgets.QLabel(self.widget)
        self.label_info.setObjectName("label_info")
        self.gridLayout_13.addWidget(self.label_info, 2, 0, 1, 1)
        self.lineEdit_info = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_info.setObjectName("lineEdit_info")
        self.gridLayout_13.addWidget(self.lineEdit_info, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 3, 0, 1, 1)
        self.comboBox_eutid = QtWidgets.QComboBox(self.widget)
        self.comboBox_eutid.setObjectName("comboBox_eutid")
        self.gridLayout_13.addWidget(self.comboBox_eutid, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 7, 0, 1, 1)
        self.comboBox_sensortyplistid = QtWidgets.QComboBox(self.widget)
        self.comboBox_sensortyplistid.setObjectName("comboBox_sensortyplistid")
        self.gridLayout_13.addWidget(self.comboBox_sensortyplistid, 7, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.widget)
        self.label_83.setObjectName("label_83")
        self.gridLayout_13.addWidget(self.label_83, 4, 0, 1, 1)
        self.comboBox_ambtempid = QtWidgets.QComboBox(self.widget)
        self.comboBox_ambtempid.setObjectName("comboBox_ambtempid")
        self.gridLayout_13.addWidget(self.comboBox_ambtempid, 4, 1, 1, 1)
        self.gridLayout_17.addWidget(self.widget, 3, 0, 1, 2)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setStyleSheet("")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_maxColumnName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_maxColumnName.setObjectName("lineEdit_maxColumnName")
        self.gridLayout_3.addWidget(self.lineEdit_maxColumnName, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 2, 1)
        self.lineEdit_sensornameColumnName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_sensornameColumnName.setObjectName("lineEdit_sensornameColumnName")
        self.gridLayout_3.addWidget(self.lineEdit_sensornameColumnName, 4, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 4, 0, 2, 1)
        self.checkBox_addfromFileClumnname = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_addfromFileClumnname.setObjectName("checkBox_addfromFileClumnname")
        self.gridLayout_3.addWidget(self.checkBox_addfromFileClumnname, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget_8)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_sensorNameid = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_sensorNameid.setObjectName("comboBox_sensorNameid")
        self.gridLayout_2.addWidget(self.comboBox_sensorNameid, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_sensorMaxValueid = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_sensorMaxValueid.setObjectName("comboBox_sensorMaxValueid")
        self.gridLayout_2.addWidget(self.comboBox_sensorMaxValueid, 0, 1, 1, 1)
        self.comboBox_sensorNameid.raise_()
        self.comboBox_sensorMaxValueid.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_8)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.widget_8, 4, 0, 1, 2)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_txtSpaltValue = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_txtSpaltValue.setObjectName("lineEdit_txtSpaltValue")
        self.gridLayout_12.addWidget(self.lineEdit_txtSpaltValue, 1, 3, 1, 1)
        self.btn_openfile = QtWidgets.QPushButton(self.widget_11)
        self.btn_openfile.setObjectName("btn_openfile")
        self.gridLayout_12.addWidget(self.btn_openfile, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(116, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 4, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_11)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 4, 0, 1, 2)
        self.btn_addMeasurment = QtWidgets.QPushButton(self.widget_11)
        self.btn_addMeasurment.setStyleSheet("")
        self.btn_addMeasurment.setObjectName("btn_addMeasurment")
        self.gridLayout_12.addWidget(self.btn_addMeasurment, 4, 3, 1, 1)
        self.lineEdit_fileName = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_fileName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.gridLayout_12.addWidget(self.lineEdit_fileName, 3, 1, 1, 3)
        self.label_20 = QtWidgets.QLabel(self.widget_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 4)
        self.gridLayout_17.addWidget(self.widget_11, 5, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_5, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.toolBox_2 = QtWidgets.QToolBox(self.widget_2)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 983, 705))
        self.page_3.setObjectName("page_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_16.addWidget(self.textEdit, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 1026, 692))
        self.page_4.setObjectName("page_4")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.widget_3 = QtWidgets.QWidget(self.page_4)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_14.addWidget(self.listWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_eut = QtWidgets.QWidget()
        self.tab_eut.setObjectName("tab_eut")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_eut)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.list_eut = QtWidgets.QListWidget(self.tab_eut)
        self.list_eut.setObjectName("list_eut")
        item = QtWidgets.QListWidgetItem()
        self.list_eut.addItem(item)
        self.gridLayout_7.addWidget(self.list_eut, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_eut)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_eut, "")
        self.tab_testLoad = QtWidgets.QWidget()
        self.tab_testLoad.setObjectName("tab_testLoad")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_testLoad)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.list_testLoad = QtWidgets.QListWidget(self.tab_testLoad)
        self.list_testLoad.setObjectName("list_testLoad")
        self.gridLayout_5.addWidget(self.list_testLoad, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_testLoad, "")
        self.tab_sensorName = QtWidgets.QWidget()
        self.tab_sensorName.setObjectName("tab_sensorName")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_sensorName)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_10 = QtWidgets.QLabel(self.tab_sensorName)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 0, 0, 1, 1)
        self.list_sensorName = QtWidgets.QListWidget(self.tab_sensorName)
        self.list_sensorName.setObjectName("list_sensorName")
        self.gridLayout_9.addWidget(self.list_sensorName, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.tab_sensorName)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_4 = QtWidgets.QFrame(self.widget_4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 1, 1, 1)
        self.lineEdit_sensorName_name = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sensorName_name.setObjectName("lineEdit_sensorName_name")
        self.gridLayout_8.addWidget(self.lineEdit_sensorName_name, 1, 0, 1, 1)
        self.lineEdit_sensorName_CSV = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sensorName_CSV.setObjectName("lineEdit_sensorName_CSV")
        self.gridLayout_8.addWidget(self.lineEdit_sensorName_CSV, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 2, 1, 1, 1)
        self.lineEdit_sensorName_fileDelimiter = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sensorName_fileDelimiter.setObjectName("lineEdit_sensorName_fileDelimiter")
        self.gridLayout_8.addWidget(self.lineEdit_sensorName_fileDelimiter, 3, 0, 1, 1)
        self.lineEdit_sensorName_fileColumn = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sensorName_fileColumn.setObjectName("lineEdit_sensorName_fileColumn")
        self.gridLayout_8.addWidget(self.lineEdit_sensorName_fileColumn, 3, 1, 1, 1)
        self.gridLayout_23.addWidget(self.frame_4, 0, 0, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem3, 0, 1, 2, 1)
        self.btn_createSensorName = QtWidgets.QPushButton(self.widget_4)
        self.btn_createSensorName.setObjectName("btn_createSensorName")
        self.gridLayout_23.addWidget(self.btn_createSensorName, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.widget_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sensorName, "")
        self.tab_sensorMax = QtWidgets.QWidget()
        self.tab_sensorMax.setObjectName("tab_sensorMax")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_sensorMax)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_9 = QtWidgets.QWidget(self.tab_sensorMax)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_sensormaxCSV = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_sensormaxCSV.setObjectName("lineEdit_sensormaxCSV")
        self.gridLayout_10.addWidget(self.lineEdit_sensormaxCSV, 1, 2, 1, 1)
        self.btn_createSensorMax = QtWidgets.QPushButton(self.widget_9)
        self.btn_createSensorMax.setObjectName("btn_createSensorMax")
        self.gridLayout_10.addWidget(self.btn_createSensorMax, 1, 4, 1, 1)
        self.lineEdit_sensormaxlisname = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_sensormaxlisname.setObjectName("lineEdit_sensormaxlisname")
        self.gridLayout_10.addWidget(self.lineEdit_sensormaxlisname, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_9)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_9)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 1, 3, 1, 1)
        self.gridLayout_11.addWidget(self.widget_9, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_sensorMax)
        self.label_11.setObjectName("label_11")
        self.gridLayout_11.addWidget(self.label_11, 0, 0, 1, 1)
        self.list_sensorMax = QtWidgets.QListWidget(self.tab_sensorMax)
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        self.list_sensorMax.setFont(font)
        self.list_sensorMax.setObjectName("list_sensorMax")
        self.gridLayout_11.addWidget(self.list_sensorMax, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sensorMax, "")
        self.tab_sensorTypList = QtWidgets.QWidget()
        self.tab_sensorTypList.setObjectName("tab_sensorTypList")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_sensorTypList)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_sensorTypList)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.frame_16 = QtWidgets.QFrame(self.tab_3)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.list_sensorTypListofLists = QtWidgets.QListWidget(self.frame_16)
        self.list_sensorTypListofLists.setObjectName("list_sensorTypListofLists")
        self.gridLayout_39.addWidget(self.list_sensorTypListofLists, 1, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.frame_16)
        self.label_82.setObjectName("label_82")
        self.gridLayout_39.addWidget(self.label_82, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.frame_16, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_5 = QtWidgets.QFrame(self.tab_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.widget_10 = QtWidgets.QWidget(self.frame_5)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.frame_14 = QtWidgets.QFrame(self.widget_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.label_77 = QtWidgets.QLabel(self.frame_14)
        self.label_77.setObjectName("label_77")
        self.gridLayout_34.addWidget(self.label_77, 0, 0, 1, 1)
        self.comboBox_41 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_41.setObjectName("comboBox_41")
        self.gridLayout_34.addWidget(self.comboBox_41, 0, 1, 1, 1)
        self.comboBox_42 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_42.setObjectName("comboBox_42")
        self.gridLayout_34.addWidget(self.comboBox_42, 1, 1, 1, 1)
        self.comboBox_43 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_43.setObjectName("comboBox_43")
        self.gridLayout_34.addWidget(self.comboBox_43, 2, 1, 1, 1)
        self.comboBox_44 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_44.setObjectName("comboBox_44")
        self.gridLayout_34.addWidget(self.comboBox_44, 3, 1, 1, 1)
        self.comboBox_45 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_45.setObjectName("comboBox_45")
        self.gridLayout_34.addWidget(self.comboBox_45, 4, 1, 1, 1)
        self.comboBox_46 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_46.setObjectName("comboBox_46")
        self.gridLayout_34.addWidget(self.comboBox_46, 5, 1, 1, 1)
        self.comboBox_47 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_47.setObjectName("comboBox_47")
        self.gridLayout_34.addWidget(self.comboBox_47, 6, 1, 1, 1)
        self.comboBox_48 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_48.setObjectName("comboBox_48")
        self.gridLayout_34.addWidget(self.comboBox_48, 7, 1, 1, 1)
        self.comboBox_49 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_49.setObjectName("comboBox_49")
        self.gridLayout_34.addWidget(self.comboBox_49, 8, 1, 1, 1)
        self.comboBox_50 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_50.setObjectName("comboBox_50")
        self.gridLayout_34.addWidget(self.comboBox_50, 9, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.frame_14)
        self.label_78.setObjectName("label_78")
        self.gridLayout_34.addWidget(self.label_78, 9, 0, 1, 1)
        self.gridLayout_36.addWidget(self.frame_14, 1, 4, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.widget_10)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.comboBox_12 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_31.addWidget(self.comboBox_12, 1, 1, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_31.addWidget(self.comboBox_13, 2, 1, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_31.addWidget(self.comboBox_11, 0, 1, 1, 1)
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_14.setObjectName("comboBox_14")
        self.gridLayout_31.addWidget(self.comboBox_14, 3, 1, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_15.setObjectName("comboBox_15")
        self.gridLayout_31.addWidget(self.comboBox_15, 4, 1, 1, 1)
        self.comboBox_16 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_16.setObjectName("comboBox_16")
        self.gridLayout_31.addWidget(self.comboBox_16, 5, 1, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_17.setObjectName("comboBox_17")
        self.gridLayout_31.addWidget(self.comboBox_17, 6, 1, 1, 1)
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout_31.addWidget(self.comboBox_18, 7, 1, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_19.setObjectName("comboBox_19")
        self.gridLayout_31.addWidget(self.comboBox_19, 8, 1, 1, 1)
        self.comboBox_20 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_20.setObjectName("comboBox_20")
        self.gridLayout_31.addWidget(self.comboBox_20, 9, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_8)
        self.label_43.setObjectName("label_43")
        self.gridLayout_31.addWidget(self.label_43, 9, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_8)
        self.label_42.setObjectName("label_42")
        self.gridLayout_31.addWidget(self.label_42, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.frame_8, 1, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.widget_10)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_30.addWidget(self.comboBox_3, 2, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_30.addWidget(self.comboBox_4, 3, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_30.addWidget(self.comboBox_5, 4, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_30.addWidget(self.label_39, 9, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_30.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_30.addWidget(self.comboBox_6, 5, 2, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_30.addWidget(self.comboBox_7, 6, 2, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_30.addWidget(self.comboBox_8, 7, 2, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_30.addWidget(self.comboBox_9, 8, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_30.addWidget(self.comboBox_10, 9, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_30.addWidget(self.label_28, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_7)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_30.addWidget(self.comboBox, 0, 2, 1, 1)
        self.gridLayout_36.addWidget(self.frame_7, 1, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.widget_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_46 = QtWidgets.QLabel(self.frame_13)
        self.label_46.setObjectName("label_46")
        self.gridLayout_33.addWidget(self.label_46, 0, 0, 1, 1)
        self.comboBox_31 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_31.setObjectName("comboBox_31")
        self.gridLayout_33.addWidget(self.comboBox_31, 0, 1, 1, 1)
        self.comboBox_32 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_32.setObjectName("comboBox_32")
        self.gridLayout_33.addWidget(self.comboBox_32, 1, 1, 1, 1)
        self.comboBox_33 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_33.setObjectName("comboBox_33")
        self.gridLayout_33.addWidget(self.comboBox_33, 2, 1, 1, 1)
        self.comboBox_34 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_34.setObjectName("comboBox_34")
        self.gridLayout_33.addWidget(self.comboBox_34, 3, 1, 1, 1)
        self.comboBox_35 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_35.setObjectName("comboBox_35")
        self.gridLayout_33.addWidget(self.comboBox_35, 4, 1, 1, 1)
        self.comboBox_36 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_36.setObjectName("comboBox_36")
        self.gridLayout_33.addWidget(self.comboBox_36, 5, 1, 1, 1)
        self.comboBox_37 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_37.setObjectName("comboBox_37")
        self.gridLayout_33.addWidget(self.comboBox_37, 6, 1, 1, 1)
        self.comboBox_38 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_38.setObjectName("comboBox_38")
        self.gridLayout_33.addWidget(self.comboBox_38, 7, 1, 1, 1)
        self.comboBox_39 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_39.setObjectName("comboBox_39")
        self.gridLayout_33.addWidget(self.comboBox_39, 8, 1, 1, 1)
        self.comboBox_40 = QtWidgets.QComboBox(self.frame_13)
        self.comboBox_40.setObjectName("comboBox_40")
        self.gridLayout_33.addWidget(self.comboBox_40, 9, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.frame_13)
        self.label_76.setObjectName("label_76")
        self.gridLayout_33.addWidget(self.label_76, 9, 0, 1, 1)
        self.gridLayout_36.addWidget(self.frame_13, 1, 3, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.widget_10)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_44 = QtWidgets.QLabel(self.frame_9)
        self.label_44.setObjectName("label_44")
        self.gridLayout_32.addWidget(self.label_44, 0, 0, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_21.setObjectName("comboBox_21")
        self.gridLayout_32.addWidget(self.comboBox_21, 0, 1, 1, 1)
        self.comboBox_22 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_22.setObjectName("comboBox_22")
        self.gridLayout_32.addWidget(self.comboBox_22, 1, 1, 1, 1)
        self.comboBox_23 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_23.setObjectName("comboBox_23")
        self.gridLayout_32.addWidget(self.comboBox_23, 2, 1, 1, 1)
        self.comboBox_24 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_24.setObjectName("comboBox_24")
        self.gridLayout_32.addWidget(self.comboBox_24, 3, 1, 1, 1)
        self.comboBox_25 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_25.setObjectName("comboBox_25")
        self.gridLayout_32.addWidget(self.comboBox_25, 4, 1, 1, 1)
        self.comboBox_26 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_26.setObjectName("comboBox_26")
        self.gridLayout_32.addWidget(self.comboBox_26, 5, 1, 1, 1)
        self.comboBox_27 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_27.setObjectName("comboBox_27")
        self.gridLayout_32.addWidget(self.comboBox_27, 6, 1, 1, 1)
        self.comboBox_28 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_28.setObjectName("comboBox_28")
        self.gridLayout_32.addWidget(self.comboBox_28, 7, 1, 1, 1)
        self.comboBox_29 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_29.setObjectName("comboBox_29")
        self.gridLayout_32.addWidget(self.comboBox_29, 8, 1, 1, 1)
        self.comboBox_30 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_30.setObjectName("comboBox_30")
        self.gridLayout_32.addWidget(self.comboBox_30, 9, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_9)
        self.label_45.setObjectName("label_45")
        self.gridLayout_32.addWidget(self.label_45, 9, 0, 1, 1)
        self.gridLayout_36.addWidget(self.frame_9, 1, 2, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.widget_10)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_79 = QtWidgets.QLabel(self.frame_15)
        self.label_79.setObjectName("label_79")
        self.gridLayout_35.addWidget(self.label_79, 0, 0, 1, 1)
        self.comboBox_51 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_51.setObjectName("comboBox_51")
        self.gridLayout_35.addWidget(self.comboBox_51, 0, 1, 1, 1)
        self.comboBox_52 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_52.setObjectName("comboBox_52")
        self.gridLayout_35.addWidget(self.comboBox_52, 1, 1, 1, 1)
        self.comboBox_53 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_53.setObjectName("comboBox_53")
        self.gridLayout_35.addWidget(self.comboBox_53, 2, 1, 1, 1)
        self.comboBox_54 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_54.setObjectName("comboBox_54")
        self.gridLayout_35.addWidget(self.comboBox_54, 3, 1, 1, 1)
        self.comboBox_55 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_55.setObjectName("comboBox_55")
        self.gridLayout_35.addWidget(self.comboBox_55, 4, 1, 1, 1)
        self.comboBox_56 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_56.setObjectName("comboBox_56")
        self.gridLayout_35.addWidget(self.comboBox_56, 5, 1, 1, 1)
        self.comboBox_57 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_57.setObjectName("comboBox_57")
        self.gridLayout_35.addWidget(self.comboBox_57, 6, 1, 1, 1)
        self.comboBox_58 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_58.setObjectName("comboBox_58")
        self.gridLayout_35.addWidget(self.comboBox_58, 7, 1, 1, 1)
        self.comboBox_59 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_59.setObjectName("comboBox_59")
        self.gridLayout_35.addWidget(self.comboBox_59, 8, 1, 1, 1)
        self.comboBox_60 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_60.setObjectName("comboBox_60")
        self.gridLayout_35.addWidget(self.comboBox_60, 9, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.frame_15)
        self.label_80.setObjectName("label_80")
        self.gridLayout_35.addWidget(self.label_80, 9, 0, 1, 1)
        self.gridLayout_36.addWidget(self.frame_15, 1, 5, 1, 1)
        self.gridLayout_37.addWidget(self.widget_10, 1, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.frame_5)
        self.label_81.setObjectName("label_81")
        self.gridLayout_37.addWidget(self.label_81, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.tab_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.lineEdit_createSensorTypList2_name = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_createSensorTypList2_name.setObjectName("lineEdit_createSensorTypList2_name")
        self.gridLayout_29.addWidget(self.lineEdit_createSensorTypList2_name, 0, 0, 1, 1)
        self.btn_createSensorTypList2 = QtWidgets.QPushButton(self.frame_6)
        self.btn_createSensorTypList2.setObjectName("btn_createSensorTypList2")
        self.gridLayout_29.addWidget(self.btn_createSensorTypList2, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_6, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.gridLayout_21.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sensorTypList, "")
        self.gridLayout_6.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.widget_3, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_4, "")
        self.gridLayout_22.addWidget(self.toolBox_2, 0, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem5, 1, 0, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(self.widget_2)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout_22.addWidget(self.btn_exit, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.toolBox_2.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_24.setText(_translate("Form", "Create climatic measurement"))
        self.label_21.setText(_translate("Form", "Create a climatic Measurement entry in the database"))
        self.btn_loadData.setText(_translate("Form", "load data from database"))
        self.label_23.setText(_translate("Form", "Datum:"))
        self.dateTimeEdit.setDisplayFormat(_translate("Form", "yyyy.MM.dd-HH:mm:ss"))
        self.label_name.setText(_translate("Form", "Name:"))
        self.label_info.setText(_translate("Form", "Info:"))
        self.label_2.setText(_translate("Form", "EUT: (id)"))
        self.label.setText(_translate("Form", "Test Load: (id)"))
        self.label_7.setText(_translate("Form", "SensorTyp List: (id)"))
        self.label_83.setText(_translate("Form", "Ambient Temp.: (id)"))
        self.groupBox_2.setTitle(_translate("Form", "Add Measurment (new max name)"))
        self.lineEdit_maxColumnName.setText(_translate("Form", "max"))
        self.label_8.setText(_translate("Form", "Sensor Max Value"))
        self.lineEdit_sensornameColumnName.setText(_translate("Form", "name"))
        self.label_19.setText(_translate("Form", "SensorName"))
        self.checkBox_addfromFileClumnname.setText(_translate("Form", "add_measurment and define new "))
        self.groupBox.setTitle(_translate("Form", "Add Measurement (with max_id, name_id)"))
        self.label_6.setText(_translate("Form", "Sensor Max Value (ID)"))
        self.label_5.setText(_translate("Form", "SensorName (ID)"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">create a measurement</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Option A:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">with id s</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Option B:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">from csv file with the column names</p></body></html>"))
        self.lineEdit_txtSpaltValue.setText(_translate("Form", "temp"))
        self.btn_openfile.setText(_translate("Form", "open File"))
        self.label_18.setText(_translate("Form", "Spalten name im file (z.B. value)"))
        self.btn_addMeasurment.setText(_translate("Form", "add measurement"))
        self.label_20.setText(_translate("Form", "Select a file with the temp Values"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600; text-decoration: underline;\">  Create Climatic  </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600; text-decoration: underline;\">  Measurment GUI  </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">            import values by csv-File</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Beschreibung:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Anforderungen an die CSV datei:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Delimiter = &quot;,&quot;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mindestensanzahl Zeilen = 61</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zeile 1: (Head Line der CSV Datei)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- SpalteA    name    = Name des Sensors</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- SpalteB    max    = Maximalzulaessiger Wert des Sensors</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- SpalteC    value    = Gemessennerwert des Sensors</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zeile 2 - 61: (Werte Zeilen)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    Die werte von Splate A,B,C,</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Zeile 62</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    in dieser Zeile solte bei name(SpalteA) &quot;ENDE&quot; stehen</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    damit die CSV Datei auch sicher mindesten 61 Zeilen gross ist.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Sebastian Schilling</p></body></html>"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_3), _translate("Form", "Read Me"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Measurments"))
        __sortingEnabled = self.list_eut.isSortingEnabled()
        self.list_eut.setSortingEnabled(False)
        item = self.list_eut.item(0)
        item.setText(_translate("Form", "Listen font = Courier 10 Pitch, 11, regular"))
        self.list_eut.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_eut), _translate("Form", "EUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_testLoad), _translate("Form", "Test Load"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_13.setText(_translate("Form", "NAME: (of sensor-name-list)"))
        self.label_14.setText(_translate("Form", "File Name: (load from file)"))
        self.lineEdit_sensorName_name.setText(_translate("Form", "namelist name"))
        self.lineEdit_sensorName_CSV.setText(_translate("Form", "m1.csv"))
        self.label_17.setText(_translate("Form", "Delimiter of the File:"))
        self.label_27.setText(_translate("Form", "Column Name: "))
        self.lineEdit_sensorName_fileDelimiter.setText(_translate("Form", ","))
        self.lineEdit_sensorName_fileColumn.setText(_translate("Form", "name"))
        self.btn_createSensorName.setText(_translate("Form", "Create Sensor Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sensorName), _translate("Form", "Sensor Name"))
        self.lineEdit_sensormaxCSV.setText(_translate("Form", "m1.csv"))
        self.btn_createSensorMax.setText(_translate("Form", "Create Sensor Max"))
        self.lineEdit_sensormaxlisname.setText(_translate("Form", "name"))
        self.label_4.setText(_translate("Form", "Load from File: (datei name)"))
        self.label_3.setText(_translate("Form", "Name: (sensorMaxList)"))
        self.label_11.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sensorMax), _translate("Form", "Sensor Max"))
        self.label_82.setText(_translate("Form", "List of all SensorTyp Lists:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "View Typ List"))
        self.label_77.setText(_translate("Form", "41"))
        self.label_78.setText(_translate("Form", "50"))
        self.label_43.setText(_translate("Form", "20"))
        self.label_42.setText(_translate("Form", "11"))
        self.label_39.setText(_translate("Form", "Sendor 10"))
        self.label_28.setText(_translate("Form", "Sensor 1"))
        self.label_46.setText(_translate("Form", "31"))
        self.label_76.setText(_translate("Form", "40"))
        self.label_44.setText(_translate("Form", "21"))
        self.label_45.setText(_translate("Form", "30"))
        self.label_79.setText(_translate("Form", "51"))
        self.label_80.setText(_translate("Form", "60"))
        self.label_81.setText(_translate("Form", "Define the Sensor Type List"))
        self.btn_createSensorTypList2.setText(_translate("Form", "PushButton"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "Create Typ List"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sensorTypList), _translate("Form", "Sensor Typ List"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("Form", "Climatic Measurment Data"))
        self.btn_exit.setText(_translate("Form", "EXIT"))

